### ISSUE TITLE
.csv to .xlsx Converter

### ISSUE THREAD

**Issue by diego-ons** [tech-acs/crvsreportpackage#16]
## Description

One function that is necessary is something that will convert all produced `.csv` files into `.xlsx` for easier conversion.
I am unsure where this should live. Also, there should be a configurable parameter in `crvs_report` that will determine the final output of the tables.

## Acceptance Criteria

- [ ] A function that will take the `.csv` files and will produce `.xlsx` files.
- [ ] A configurable parameter in `crvs_report` for users to select the output.

**Comment by rcatlord** [comment]
It might need some finessing but this converts multiple `.csv` files into separate Excel worksheets:

```r
csv_to_excel <- function(path = ".") {
  file_list <- list.files(path = path, pattern = "*.csv", full.names = F)
  
  table_list <- file_list |> 
    purrr::map(~readr::read_csv(.), .id = "id") |> 
    purrr::set_names(tools::file_path_sans_ext(fs::path_file(file_list)))
  
  writexl::write_xlsx(table_list, "output.xlsx")
}

csv_to_excel(path = ".")
```

**Comment by diego-ons** [comment]
Function added to the package
