### ISSUE TITLE
Unit tests for round_excel.R are created

### ISSUE THREAD

**Issue by diego-ons** [tech-acs/crvsreportpackage#2]
## Description

In order to start with unit test creation, a simple function to tackle is the one in `round_excel.R`. This function simple rounds a value to the specified number of decimal places using Excel method. It should be easy to create some tests and gain confidence in how these are done. Also to gain practice with the contribution style that we are implementing.

If you have any issues with creating this test, reach out to @diego-ons ! 

## Acceptance Criteira

- [ ] A new branch from the `development` branch has been created to work on this issue.
- [ ] New tests have been added to check that the `round_excel` function works correctly in three different cases.
- [ ] These new tests have been run successfully.
- [ ] A new pull request following the approach in the `CONTRIBUTING.md` file has been created.

**Comment by tbelay** [comment]
Pull request is sent in response to this issue

**Comment by diego-ons** [comment]
This was great @tbelay ! all merged into the development branch.
Check out the new functionality, so that now when a change is made, GitHub Actions will automatically check all the tests pass!
