### ISSUE TITLE
Establish the data flow across the package

### ISSUE THREAD

**Issue by diego-ons** [tech-acs/crvsreportpackage#3]
## Description

In order to understand what data we need to have for each country, we need a data mapping from the input to the output tables.
This should allow for a clear understanding of what tables are and aren't possible given the presented data.

## Acceptance Criteria

- [x] A document that will show what data variables are necessary for each output table.
- [x] The information has been added to the package in a vignette (linked to issue #1 )
- [x] A data dictionary has been created containing all the variables needed to produce all the output tables

**Comment by rcatlord** [comment]
I have pushed the [henry_dev](https://github.com/tech-acs/crvsreportpackage/tree/henry_dev) branch which includes a draft 'data_mapping' vignette and corresponding data. This includes a [data dictionary](https://github.com/tech-acs/crvsreportpackage/blob/henry_dev/vignettes/data/data_dictionary.csv), i.e. a list of variables required for CRVS reporting. I intend to add data types (e.g. string, date, float etc) and example values.

The vignette also includes an [interactive table](https://github.com/tech-acs/crvsreportpackage/blob/henry_dev/vignettes/data_mapping.Rmd) showing all the first priority CRVS tables and all of the variables required to populate them. You will need to render the .Rmd file locally to view the HTML.

Is it possible to validate / augment the list of variables with the variables that Pamela mentioned?

**Comment by rcatlord** [comment]
Also, please note that the variable IDs are a concatenation of the registration event (birth, death etc) and the variable references used in the [Vital Strategies Excel template](https://www.vitalstrategies.org/resources/production-of-a-vital-statistics-report/).
