### ISSUE TITLE
All of the development team should have access to the repo

### ISSUE THREAD

**Issue by diego-ons** [tech-acs/crvsreportpackage#4]
## Description

In order to work on the repository, all of the six team members should have access to the repo and be able to:

- Clone the repository
- Make new branches and commit changes
- Run the full test suite
- Create a pull request and review another one
- Create a new issue

Please leave a comment on this issue once you have done all of these.

**Comment by RachelS-ONS** [comment]
Hi, I have tried to clone the repository but it is asking me for a certificate: fatal: unable to access 'https://github.com/tech-acs/crvsreportpackage.git/': SSL certificate problem: unable to get local issuer certificate

**Comment by RachelS-ONS** [comment]
Please can Liam be added git handle is beardl-ons

**Comment by diego-ons** [comment]
> Please can Liam be added git handle is beardl-ons

I have added him now, thanks.



> Hi, I have tried to clone the repository but it is asking me for a certificate: fatal: unable to access 'https://github.com/tech-acs/crvsreportpackage.git/': SSL certificate problem: unable to get local issuer certificate

This seems to be a set-up problem on the machine. I will have a look this afternoon, but on super quick inspection [this article might be useful.](https://komodor.com/learn/how-to-fix-ssl-certificate-problem-unable-to-get-local-issuer-certificate-git-error/)
