### ISSUE TITLE
documentation - mapping variables - Table 2 appears to be missing T4_1

### ISSUE THREAD

**Issue by jeroenminderman** [tech-acs/crvsreportpackage#42]
https://tech-acs.github.io/crvsreportpackage/articles/data_mapping.html

**Comment by rcatlord** [comment]
Table 4.1 is now included in Table 2 after an [update](https://tech-acs.github.io/crvsreportpackage/articles/data_mapping.html) to the 'Mapping variables to outputs' vignette.
