### ISSUE TITLE
Data Cleaning using `pointblank`

### ISSUE THREAD

**Issue by diego-ons** [tech-acs/crvsreportpackage#50]
## Description

Throughout the visits we have used `pointblank` as a tool for data cleaning and validation.
We should update the _data cleaning_ vignette to implement a `pointblank` agent with some of the validation rules that we have used in the past.

This could also be in the form of a new script in the `scripts` folder so that we can pull and swap the incoming dataset.

## Acceptance Criteria

- [ ] Update the data cleaning vignette to implement pointblank and the validation rules used in the visits.
- [ ] A script version that can be used off-the-shelf by NSOs to do their data validation.

**Comment by diego-ons** [comment]
Thanks @gulilattesfaye for this, I have added a modified version of your script to the crvs_report repo.

**Comment by gulilattesfaye** [comment]
Thanks. I did not get the modified version.
